import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from '@/styles/main-layout.module.scss';
import Header from './components/Header';
import Search from './components/Search';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Alex's Movies app",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className + ' ' + styles.body}>
        <Header />
        <main className={styles.main}>
          <Search />
          {children}
        </main>
      </body>
    </html>
  );
}
